### PR TITLE
Update READMEs

### PR DESCRIPTION
**Pull request by xhs**
Hi Cameron, I have fixed a typo in function response.
And the guides to upload firmware can be misleading (at least to me), so I also made some adjustments.
Also bumped the dependencies to their latest versions except those not supported.

### CODE REVIEW

**Comment by cesarhernandezgt** [comment]
Hi @xhs @cameronsenese 
I couldn't test this PR or master branch because when I do a:

`screen /dev/tty.wchusbserial14310 115200`

I get the following errors:
`Cannot open line `/dev/tty.wchusbserial14310` for R/W: Resource busy
followed by:
`Sorry, could not find a PTY.`

Then I tried the electron terminal without luck after typing `help`:
image

I even try with different drivers like this ones mentioned here without luck: https://github.com/noelportugal/codecard/issues/4#issuecomment-435086934

My env: OSX 10.14.5, using a usbc-usb adapter since I only have usb c type ports.
Tried also with different cables.

Any idea or pointer?

**Comment by xhs** [comment]
Hi @cesarhernandezgt ,
I think the device should be /dev/cu.XXX.

BTW, in HTTP/1.0 it seems OK to have host in path, this PR may not be necessary if you have changed all HTTP/1.1 to HTTP/1.0 and your API servers are OK with HTTP/1.0.

**Comment by cameronsenese** [comment]
Hi @cesarhernandezgt,
To confirm - the correct drivers (Windows & Mac) are available over here: https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers.

**Comment by cesarhernandezgt** [comment]
thanks much for your quick reply and detail pointers.
I was able to connect with the card, two lessons learned from my side:

1. Use a proper cable. It seems a common issue is to try to use cables that only works for charging devices, this type of cables doesn't work.  https://github.com/noelportugal/codecard/issues/4#issuecomment-436691522

2. After installed correct drivers and opening the electron terminal. A simultaneous a+b shot press in the card buttons is mandatory to allow the card to enter in configuration mode.

**Comment by cameronsenese** [comment]
Thanks @cesarhernandezgt,
Will update docs to remind folks about cables & the A+B shortpress to kick-off the terminal session.

Cheers!

**Comment by sanjay92-gupta** [comment]
Got Code card from Oracle Open World 2019. I have download Code Terminal on MAC and installed driver usb-to-uart-bridge-vcp-drivers  and I am using correct cable. Code Terminal says Card Not Detected. I see following 
rw-rw-rw-  1 root  wheel   18,  11 Sep 20 22:13 /dev/cu.SLAB_USBtoUART

I can do screen /dev/cu.SLAB_USBtoUART 9600 but it displays junk characters. 
I need to reconfigure wifi

**Comment by cameronsenese** [comment]
Sounds like you are Ok now?
If having issues with the Code Card Terminal, Suggest you follow: https://github.com/cameronsenese/codecard/blob/master/terminal/README.md#connect-via-terminal-emulator

Or, you can use the Code Card Configurator script: https://github.com/cameronsenese/codecard-configurator
Just update the WiFi settings in the script & run..

**Comment by sanjay92-gupta** [comment]
yeah, Thanks. 
Looking what we could do with code card. Any more documentation on how to use it. I can put my name and icon using template ( oracle event app). How could I upload my image ?

**Comment by suztomo** [comment]
@sanjay92-gupta I found the JSON spec with image selection below. It says you can choose one of the 100 icons.
https://github.com/cameronsenese/codecard/tree/master/functions#create-a-fn-function-for-your-code-card

@cameronsenese Would you share how to update the HTTP URL from which Code Card fetches the JSON?

**Comment by suztomo** [comment]
It's `buttona1` and `buttonb1` with corresponding fingerprint in `fingerprinta1` and `fingerprintb1`.

```
~ $ openssl s_client -connect apex.oracle.com:443 < /dev/null 2>/dev/null | openssl x509 -fingerprint -noout -in /dev/stdin
SHA1 Fingerprint=8B:8A:B0:33:DE:B9:77:A7:4D:D1:7D:48:EB:DD:FF:15:4D:51:E0:A6
```

https://github.com/cameronsenese/codecard/blob/master/arduino/codecard/buttonEvents.h#L21

**Comment by sanjay92-gupta** [comment]
SHA fingerprint was changed and now it points to

penssl s_client -connect apex.oracle.com:443 < /dev/null 2>/dev/null | openssl x509 -fingerprint -noout -in /dev/stdin
SHA1 Fingerprint=60:E4:E7:41:78:B7:EB:4C:75:08:88:25:50:42:61:CE:55:9C:80:FD


which I have changed


My Oracle Code card is not working anymore. I am getting  Unexpected response: HTTP/1.0 200 OK

On Code Card, I only see A Short Pressed , please wait....



Request:
  host: apex.oracle.com
  port: 443
  url: https://apex.oracle.com/pls/apex/appslab/functions/master
  fingerprint: 60 E4 E7 41 78 B7 EB 4C 75 08 88 25 50 42 61 CE 55 9C 80 FD
  method: GET
  Unexpected response: HTTP/1.0 200 OK

**Comment by suztomo** [comment]
The unexpected response error comes from the old Arduino code. 

https://github.com/cameronsenese/codecard/commit/58880db2f32c391abce28eda90500a4e98580d80

Code Card in Oracle 2019 did not have latest code. I had to install the latest Arduino code for my card to resolve the unexpected response error.

**Comment by sanjay92-gupta** [comment]
Hi Suztomo,
Thanks for your response. If I read your message your correctly, you want me to compile and upload new firmware by using following instructions.
https://github.com/cameronsenese/codecard/tree/master/arduino

I did follow instruction but I see compilation but it fails when uploading new firmware
Sketch uses 444156 bytes (88%) of program storage space. Maximum is 499696 bytes.
Global variables use 41700 bytes (50%) of dynamic memory, leaving 40220 bytes for local variables. Maximum is 81920 bytes.
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed

I did post issue here 
https://learncodeshare.net/2019/09/24/you-went-to-oracle-open-world-19-and-got-a-code-card-now-what/?unapproved=189&moderation-hash=6f0cb2b6ad8ac86f8ced6395e6b59242#comment-189

**Comment by suztomo** [comment]
> error: espcomm_open failed

Yes, I had got the same error. Solution: I had to hold “button A” until it starts transferring the firmware.

**Comment by sanjay92-gupta** [comment]
Thanks suztomo. It worked.

**Comment by sanjay92-gupta** [comment]
I am looking on how to upload your own logo/image. In images folder on git documentation, it says that you can upload own images but don't give any clue on how ?

**Comment by cameronsenese** [comment]
> I am looking on how to upload your own logo/image. In images folder on git documentation, it says that you can upload own images but don't give any clue on how ?

Hi sanjay92-gupta - please see the following guide: https://github.com/cameronsenese/codecard/tree/master/functions/examples/bitmap

**Pull request closed without merging**
